### ISSUE TITLE
unnable to compile bootstrap

### ISSUE THREAD

**Issue by 262media** [braginteractive/MaterialKitWP#2]
status: 1
    file: /Users/rui/materialkitwp/sass/style.scss
    line: 36
    column: 1
    formatted: Error: File to import not found or unreadable: bootstrap
       Parent style sheet: /Users/rui/materialkitwp/sass/style.scss
        on line 36 of sass/style.scss

> > @import "bootstrap";

how can i fix this?

**Comment by braginteractive** [comment]
Did you install the bower components which will include Bootstrap?

**Comment by 262media** [comment]
Yes i did bower install but they got placed in /app/components

**Comment by braginteractive** [comment]
Sounds like you have some customizations going on. You will need to change the paths in the Gulp file to your stylesheets so Gulp can find your files.

**Comment by 262media** [comment]
no customization yet. To be sure i've just cloned this repo and did the folowing:

262media:MaterialKitWP-master rui$  npm install 
npm WARN package.json MaterialKit@1.0.0 No repository field.
npm WARN package.json MaterialKit@1.0.0 No license field.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

## npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> gifsicle@3.0.4 postinstall /Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> optipng-bin@3.1.2 postinstall /Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@3.1.0 postinstall /Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> node-sass@3.10.1 install /Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.1/darwin-x64-46_binding.node
Binary downloaded and installed at /Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> fsevents@1.0.14 install /Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@3.10.1 postinstall /Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

"/Users/rui/Downloads/MaterialKitWP-master/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
gulp-rename@1.2.2 node_modules/gulp-rename

jshint-stylish@1.0.2 node_modules/jshint-stylish
├── log-symbols@1.0.2
├── text-table@0.2.0
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
└── string-length@1.0.1 (strip-ansi@3.0.1)

gulp-zip@3.2.0 node_modules/gulp-zip
├── yazl@2.4.1 (buffer-crc32@0.2.5)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── concat-stream@1.5.2 (inherits@2.0.3, typedarray@0.0.6, readable-stream@2.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, beeper@1.1.0, array-uniq@1.0.3, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp-clean-css@2.0.13 node_modules/gulp-clean-css
├── object-assign@4.1.0
├── readable-stream@2.1.5 (buffer-shims@1.0.0, string_decoder@0.10.31, inherits@2.0.3, util-deprecate@1.0.2, process-nextick-args@1.0.7, core-util-is@1.0.2, isarray@1.0.0)
├── vinyl-sourcemaps-apply@0.2.1 (source-map@0.5.6)
├── vinyl-bufferstream@1.0.1 (bufferstreams@1.0.1)
├── clean-css@3.4.20 (commander@2.8.1, source-map@0.4.4)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, array-uniq@1.0.3, object-assign@3.0.0, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, chalk@1.1.3, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-plumber@1.1.0 node_modules/gulp-plumber
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reescape@3.0.0, array-uniq@1.0.3, object-assign@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, chalk@1.1.3, multipipe@0.1.2, dateformat@1.0.12)

gulp-livereload@3.8.1 node_modules/gulp-livereload
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.5, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── debug@2.2.0 (ms@0.7.1)
├── lodash.assign@3.2.0 (lodash._baseassign@3.2.0, lodash._createassigner@3.1.1, lodash.keys@3.1.2)
├── event-stream@3.3.4 (pause-stream@0.0.11, duplexer@0.1.1, stream-combiner@0.0.4, from@0.1.3, map-stream@0.1.0, split@0.3.3, through@2.3.8)
├── mini-lr@0.1.9 (parseurl@1.3.1, livereload-js@2.2.2, qs@2.2.5, body-parser@1.14.2, faye-websocket@0.7.3)
└── gulp-util@3.0.7 (array-differ@1.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, array-uniq@1.0.3, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-uglify@1.5.4 node_modules/gulp-uglify
├── uglify-save-license@0.4.1
├── deap@1.0.0
├── isobject@2.1.0 (isarray@1.0.0)
├── vinyl-sourcemaps-apply@0.2.1 (source-map@0.5.6)
├── fancy-log@1.2.0 (time-stamp@1.0.1, chalk@1.1.3)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── uglify-js@2.6.4 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, array-uniq@1.0.3, object-assign@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.12)

gulp@3.9.1 node_modules/gulp
├── interpret@1.0.1
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.2.0 (os-homedir@1.0.2)
├── minimist@1.2.0
├── v8flags@2.0.11 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── vinyl-fs@0.3.14 (strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, graceful-fs@3.0.11, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)
├── liftoff@2.3.0 (lodash.isplainobject@4.0.6, lodash.isstring@4.0.1, lodash.mapvalues@4.6.0, rechoir@0.6.2, extend@3.0.0, flagged-respawn@0.3.2, resolve@1.1.7, fined@1.0.2, findup-sync@0.4.2)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.3, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, fancy-log@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-include@1.1.1 node_modules/gulp-include
├── event-stream@3.1.7 (pause-stream@0.0.11, duplexer@0.1.1, stream-combiner@0.0.4, from@0.1.3, map-stream@0.1.0, split@0.2.10, through@2.3.8)
├── glob@4.5.3 (inherits@2.0.3, once@1.4.0, inflight@1.0.5, minimatch@2.0.10)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-notify@2.2.0 node_modules/gulp-notify
├── node.extend@1.1.6 (is@3.1.0)
├── lodash.template@3.6.2 (lodash._basevalues@3.0.0, lodash.templatesettings@3.1.1, lodash.restparam@3.6.1, lodash._isiterateecall@3.0.9, lodash._basetostring@3.0.1, lodash._reinterpolate@3.0.0, lodash._basecopy@3.0.1, lodash.escape@3.2.0, lodash.keys@3.1.2)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
├── gulp-util@3.0.7 (array-differ@1.0.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, array-uniq@1.0.3, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
└── node-notifier@4.6.1 (semver@5.3.0, shellwords@0.1.0, growly@1.3.0, minimist@1.2.0, which@1.2.11, lodash.clonedeep@3.0.2, cli-usage@0.1.4)

gulp-jshint@1.12.0 node_modules/gulp-jshint
├── minimatch@2.0.10 (brace-expansion@1.1.6)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
├── rcloader@0.1.2 (lodash@2.4.2, rcfinder@0.1.9)
├── gulp-util@3.0.7 (array-differ@1.0.0, beeper@1.1.0, array-uniq@1.0.3, lodash._reescape@3.0.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
├── lodash@3.10.1
└── jshint@2.9.3 (strip-json-comments@1.0.4, exit@0.1.2, console-browserify@1.1.0, minimatch@3.0.3, shelljs@0.3.0, cli@1.0.0, htmlparser2@3.8.3, lodash@3.7.0)

gulp-autoprefixer@2.3.1 node_modules/gulp-autoprefixer
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── postcss@4.1.16 (js-base64@2.1.9, es6-promise@2.3.0, source-map@0.4.4)
├── gulp-util@3.0.7 (array-differ@1.0.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, array-uniq@1.0.3, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, chalk@1.1.3, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
└── autoprefixer-core@5.2.1 (num2fraction@1.2.2, browserslist@0.4.0, caniuse-db@1.0.30000553)

gulp-bower@0.0.10 node_modules/gulp-bower
├── through2@0.6.2 (xtend@4.0.1, readable-stream@1.0.34)
├── walk@2.3.3 (foreachasync@3.0.0)
├── gulp-util@3.0.1 (lodash._reinterpolate@2.4.1, minimist@1.2.0, lodash@2.4.2, vinyl@0.4.6, chalk@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)
└── bower@1.7.9

gulp-imagemin@2.4.0 node_modules/gulp-imagemin
├── object-assign@4.1.0
├── plur@2.1.2 (irregular-plurals@1.2.0)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── through2-concurrent@1.1.1 (through2@2.0.1)
├── pretty-bytes@2.0.1 (get-stdin@4.0.1, number-is-nan@1.0.1, meow@3.7.0)
├── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, array-uniq@1.0.3, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
└── imagemin@4.0.0 (optional@0.1.3, stream-combiner2@1.1.1, readable-stream@2.1.5, buffer-to-vinyl@1.1.0, concat-stream@1.5.2, vinyl-fs@2.4.3, imagemin-svgo@4.2.1, imagemin-gifsicle@4.2.0, imagemin-optipng@4.3.0, imagemin-jpegtran@4.3.2)

gulp-watch@4.3.10 node_modules/gulp-watch
├── path-is-absolute@1.0.1
├── object-assign@4.1.0
├── vinyl@1.2.0 (clone-stats@0.0.1, replace-ext@0.0.1, clone@1.0.2)
├── vinyl-file@2.0.0 (pify@2.3.0, graceful-fs@4.1.9, strip-bom@2.0.0, pinkie-promise@2.0.1, strip-bom-stream@2.0.0)
├── glob-parent@3.0.0 (is-glob@3.0.0)
├── readable-stream@2.1.5 (buffer-shims@1.0.0, string_decoder@0.10.31, inherits@2.0.3, process-nextick-args@1.0.7, util-deprecate@1.0.2, core-util-is@1.0.2, isarray@1.0.0)
├── anymatch@1.3.0 (arrify@1.0.1, micromatch@2.3.11)
├── gulp-util@3.0.7 (array-differ@1.0.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, array-uniq@1.0.3, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, chalk@1.1.3, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
└── chokidar@1.6.0 (inherits@2.0.3, async-each@1.0.1, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.1.0, fsevents@1.0.14)

gulp-sass@2.3.2 node_modules/gulp-sass
├── lodash.clonedeep@4.5.0
├── vinyl-sourcemaps-apply@0.2.1 (source-map@0.5.6)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, array-uniq@1.0.3, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.12)
└── node-sass@3.10.1 (get-stdin@4.0.1, lodash.assign@4.2.0, async-foreach@0.1.3, in-publish@2.0.0, chalk@1.1.3, nan@2.4.0, mkdirp@0.5.1, cross-spawn@3.0.1, glob@7.1.1, npmlog@4.0.0, meow@3.7.0, request@2.75.0, gaze@1.1.2, node-gyp@3.4.0, sass-graph@2.1.2)
262media:MaterialKitWP-master rui$ bower install
bower cached        https://github.com/twbs/bootstrap-sass.git#3.3.7
bower validate      3.3.7 against https://github.com/twbs/bootstrap-sass.git#*
bower cached        https://github.com/FortAwesome/Font-Awesome.git#4.6.3
bower validate      4.6.3 against https://github.com/FortAwesome/Font-Awesome.git#*
bower cached        https://github.com/jquery/jquery-dist.git#3.1.1
bower validate      3.1.1 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower install       fontawesome#4.6.3
bower install       bootstrap-sass#3.3.7
bower install       jquery#3.1.1

fontawesome#4.6.3 app/components/fontawesome

bootstrap-sass#3.3.7 app/components/bootstrap-sass
└── jquery#3.1.1

jquery#3.1.1 app/components/jquery
262media:MaterialKitWP-master rui$

**Comment by 262media** [comment]
as you can see bower install puts its dependencies inside app/components/

**Comment by braginteractive** [comment]
I dunno, don't have this issue. So just Googling around. Found this: https://github.com/bower/bower/issues/1432

Like I said before, just change the paths in your Gulp file or edit the bower file to change the components folder: http://stackoverflow.com/questions/14079833/how-to-change-bowers-default-components-folder

**Comment by 262media** [comment]
Changing the paths in my Gulp file did the trick. Thank you very much

**Comment by 262media** [comment]
This probably happened because of a parent folder (or many) had a .bowerrc file like in  bower/bower#1432 . Once again thank you very much for your help and keep the good work.
